### ISSUE TITLE
exp_name = 'paviaSrc_paviaTgt'   OR   'paviaSrc2paviaTgt'

### ISSUE THREAD

**Issue by 519982073** [szubing/ED-DMM-UDA#1]
您好！打扰了！
想请问一下 main.py 中设置exp_name= 'paviaSrc2paviaTgt'和 exp_name = 'paviaSrc_paviaTgt' 分别表示什么呢？
谢谢。

**Comment by szubing** [comment]
paviaSrc2paviaTgt是表示target data 是完全无监督的；而paviaSrc_paviaTgt是半监督的，可以忽略

**Comment by szubing** [comment]
> 您好！打扰了！
> 想请问一下 main.py 中设置exp_name= 'paviaSrc2paviaTgt'和 exp_name = 'paviaSrc_paviaTgt' 分别表示什么呢？
> 谢谢。

paviaSrc2paviaTgt是表示target data 是完全无监督的；而paviaSrc_paviaTgt是半监督的，可以忽略
